### ISSUE TITLE
Bump activesupport gem dependency in gemspec

### ISSUE THREAD

**Issue by Th33x1l3** [rahmal/rconfig#11]
Can you bump activesupport version to not lock at major version 3.x

when installing your gem you downgrade activesupport to a very low version:

```
abio@fabio-LIFEBOOK-A544:~/projects/discriminator_fixes$ bundle update
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies....
Using rake 11.2.2
Using i18n 0.7.0
Using multi_json 1.12.1
Using ansi 1.5.0
Using awesome_print 1.7.0
Using builder 3.2.2
Using ffi 1.9.14
Using commonwatir 4.0.0
Using gherkin 4.0.0
Using cucumber-wire 0.0.1
Using diff-lcs 1.2.5
Using multi_test 0.1.2
Using log4r 1.1.10
Using yml_reader 0.7
Using headless 2.2.3
Using json 2.0.2
Using logger 1.2.8
Using minitest 5.9.0
Using ruby-progressbar 1.8.1
Using rubyzip 1.2.0
Using websocket 1.2.3
Using require_all 1.3.3
Using rspec-support 3.5.0
Using yard 0.9.5
Using bundler 1.12.5
Using faker 1.6.6
Using activesupport 3.2.22.4 (was 5.0.0.1)
Using childprocess 0.5.9
Using cucumber-core 1.5.0
Using minitest-reporters 1.1.11
Using rspec-core 3.5.2
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using data_magic 0.22
Using rconfig 0.5.4 (was 0.5.2)
Using selenium-webdriver 3.0.0.beta2.1
Using cucumber 2.4.0
Using rspec 3.5.0
Using page_navigation 0.9
Using watir-webdriver 0.9.3
Using crtu 0.1.1
Using page-object 1.2.0
Using watir 5.0.0
Bundle updated!

```

When trying to execute code:

```
fabio@fabio-LIFEBOOK-A544:~/projects/discriminator_fixes$ rake cucumber
/home/fabio/.rvm/rubies/ruby-2.3.0/bin/ruby -S bundle exec cucumber -r features/ --format progress --out reports/progress.out --format html --out reports/report.html --format json --out reports/cucumber.json
uninitialized constant I18n
Did you mean?  I18n (NameError)
/home/fabio/.rvm/gems/ruby-2.3.0@discriminator_fixes/gems/activesupport-3.2.22.4/lib/active_support/i18n.rb:9:in `<top (required)>'
/home/fabio/.rvm/gems/ruby-2.3.0@discriminator_fixes/gems/i18n-0.7.0/lib/i18n/version.rb:1:in `require'
/home/fabio/.rvm/gems/ruby-2.3.0@discriminator_fixes/gems/i18n-0.7.0/lib/i18n/version.rb:1:in `<top (required)>'
/home/fabio/.rvm/gems/ruby-2.3.0@discriminator_fixes/gems/i18n-0.7.0/lib/i18n.rb:1:in `require'
/home/fabio/.rvm/gems/ruby-2.3.0@discriminator_fixes/gems/i18n-0.7.0/lib/i18n.rb:1:in `<top (required)>'
/home/fabio/.rvm/gems/ruby-2.3.0@discriminator_fixes/gems/faker-1.6.6/lib/faker.rb:9:in `require'
/home/fabio/.rvm/gems/ruby-2.3.0@discriminator_fixes/gems/faker-1.6.6/lib/faker.rb:9:in `<top (required)>'
```

**Comment by rahmal** [comment]
@Th33x1l3 there was a conflict with activesupport-5.x. I'll remove that change and post the results.

**Comment by Th33x1l3** [comment]
what type of conflict?
